website/Models/ErrorViewModel.cs
using System;

namespace website.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

website/Models/SearchResult.cs
using System;

namespace website.Models
{
    public class SearchResult
    {
        public string line_id { get; set; }
        public string line_number { get; set; }
        public string play_name { get; set; }
        public string speaker { get; set; }
        public string speech_number { get; set; }
        public string text_entry { get; set; }
    }
}

website/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using website.Models;
using website.Services;

namespace website.Controllers
{
    public class HomeController : Controller
    {
        private IPlaysService playsService;

        public HomeController(IPlaysService playsService)
        {
            this.playsService = playsService;
        }

        [HttpGet]
        public async Task<IActionResult> Index([FromQuery]string input)
        {
           var result = await playsService.Select();
           return View(result.Select(r => new SearchResult
           {
               line_id = r.LineId,
               line_number = r.LineNumber,
               speech_number = r.SpeechNumber,
               play_name = r.PlayName,
               speaker = r.Speaker,
               text_entry = r.TextEntry
           }));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

website/Controllers/PlaysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using website.DataLayer.Models;
using website.Services;

namespace website.Controllers
{
    public class PlaysController : Controller
    {
        private IPlaysService playsService;

        public PlaysController()
        {
            this.playsService = playsService;
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Post(PlayModel value)
        {
            await playsService.Create(value);
            return RedirectToAction("Index", "Home");
        }
   }
}

website/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

website/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

website/Views/Home/Index.cshtml
@model IEnumerable<SearchResult>
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-md-3">
        <h3>Shakespeare plays</h2>
    </div>
</div>
<div class="row">
<form method="get"  >
  <div class="form-group">
    <input type="text" class="form-control" name="input" id="input" aria-describedby="inputHelp" placeholder="Enter text">
    <small id="inputHelp" class="form-text text-muted">Print part of phrase, role.</small>
  </div>
  <button type="submit" asp-action="Index" class="btn btn-primary">Submit</button>
</form>
</div>
<div class="row">
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.play_name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.line_number)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.speaker)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.text_entry)
                </th>

                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.play_name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.line_number)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.speaker)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.text_entry)
                    </td>
                </tr>
            }
        </tbody>
    </table>
    @Html.ActionLink("Create", "Create", "Plays")
</div>

website/Views/Plays/Create.cshtml
@model website.DataLayer.Models.PlayModel

@{
    ViewData["Title"] = "View";
}

<h2>View</h2>

<h4>PlayModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Post" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LineId" class="control-label"></label>
                <input asp-for="LineId" class="form-control" />
                <span asp-validation-for="LineId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LineNumber" class="control-label"></label>
                <input asp-for="LineNumber" class="form-control" />
                <span asp-validation-for="LineNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlayName" class="control-label"></label>
                <input asp-for="PlayName" class="form-control" />
                <span asp-validation-for="PlayName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Speaker" class="control-label"></label>
                <input asp-for="Speaker" class="form-control" />
                <span asp-validation-for="Speaker" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SpeechNumber" class="control-label"></label>
                <input asp-for="SpeechNumber" class="form-control" />
                <span asp-validation-for="SpeechNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TextEntry" class="control-label"></label>
                <input asp-for="TextEntry" class="form-control" />
                <span asp-validation-for="TextEntry" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - website</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">website</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>           
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - website</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>